// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mock/interfaces.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3Interface is a mock of S3Interface interface.
type MockS3Interface struct {
	ctrl     *gomock.Controller
	recorder *MockS3InterfaceMockRecorder
	isgomock struct{}
}

// MockS3InterfaceMockRecorder is the mock recorder for MockS3Interface.
type MockS3InterfaceMockRecorder struct {
	mock *MockS3Interface
}

// NewMockS3Interface creates a new mock instance.
func NewMockS3Interface(ctrl *gomock.Controller) *MockS3Interface {
	mock := &MockS3Interface{ctrl: ctrl}
	mock.recorder = &MockS3InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Interface) EXPECT() *MockS3InterfaceMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockS3Interface) CreateBucket(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockS3InterfaceMockRecorder) CreateBucket(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockS3Interface)(nil).CreateBucket), arg0, arg1)
}

// DeleteBucket mocks base method.
func (m *MockS3Interface) DeleteBucket(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBucket", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBucket indicates an expected call of DeleteBucket.
func (mr *MockS3InterfaceMockRecorder) DeleteBucket(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBucket", reflect.TypeOf((*MockS3Interface)(nil).DeleteBucket), arg0, arg1)
}

// DeleteObject mocks base method.
func (m *MockS3Interface) DeleteObject(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockS3InterfaceMockRecorder) DeleteObject(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockS3Interface)(nil).DeleteObject), arg0, arg1, arg2)
}

// FetchObject mocks base method.
func (m *MockS3Interface) FetchObject(arg0 context.Context, arg1, arg2 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchObject", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchObject indicates an expected call of FetchObject.
func (mr *MockS3InterfaceMockRecorder) FetchObject(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchObject", reflect.TypeOf((*MockS3Interface)(nil).FetchObject), arg0, arg1, arg2)
}

// ListBuckets mocks base method.
func (m *MockS3Interface) ListBuckets(arg0 context.Context, arg1 string) (*s3.ListBucketsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuckets", arg0, arg1)
	ret0, _ := ret[0].(*s3.ListBucketsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuckets indicates an expected call of ListBuckets.
func (mr *MockS3InterfaceMockRecorder) ListBuckets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuckets", reflect.TypeOf((*MockS3Interface)(nil).ListBuckets), arg0, arg1)
}

// ListObject mocks base method.
func (m *MockS3Interface) ListObject(arg0 context.Context, arg1, arg2 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObject", arg0, arg1, arg2)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObject indicates an expected call of ListObject.
func (mr *MockS3InterfaceMockRecorder) ListObject(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObject", reflect.TypeOf((*MockS3Interface)(nil).ListObject), arg0, arg1, arg2)
}

// PutObject mocks base method.
func (m *MockS3Interface) PutObject(arg0 context.Context, arg1, arg2 string, arg3 io.ReadSeeker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockS3InterfaceMockRecorder) PutObject(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockS3Interface)(nil).PutObject), arg0, arg1, arg2, arg3)
}
