name: Validate on Push

on:
  push:
    branches-ignore:
      - "main"

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        if: {{ github.event_name != 'pull_request' && github.event.action != 'opened' && github.event.action != 'reopened' }}
      - uses: actions/setup-go@v4
        if: {{ github.event_name != 'pull_request' && github.event.action != 'opened' && github.event.action != 'reopened' }}
        with:
          go-version: '1.23.0'
      - name: golangci-lint
        if: {{ github.event_name != 'pull_request' && github.event.action != 'opened' && github.event.action != 'reopened' }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          args: --timeout=30m
  test:
    name: Run tests
    runs-on: 'ubuntu-22.04'
    needs: lint
    steps:
      - uses: actions/checkout@v4
        if: {{ github.event_name != 'pull_request' && github.event.action != 'opened' && github.event.action != 'reopened' }}
      - uses: actions/setup-go@v4
        if: {{ github.event_name != 'pull_request' && github.event.action != 'opened' && github.event.action != 'reopened' }}
        with:
          go-version: '1.23.0'
      - name: Run go tests
        if: {{ github.event_name != 'pull_request' && github.event.action != 'opened' && github.event.action != 'reopened' }}
        run: go test -v -cover ./...
